# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ButtonAlphaAnimation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for ButtonAlphaAnimation

  target 'ButtonAlphaAnimationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ButtonAlphaAnimationUITests' do
    # Pods for testing
  end

end
