# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TextField+AdjustKeyboardHeight' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  # Pods for TextField+AdjustKeyboardHeight

  target 'TextField+AdjustKeyboardHeightTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TextField+AdjustKeyboardHeightUITests' do
    # Pods for testing
  end

end
